#!/bin/sh
set -eu

# Diverse double compilation, roadmap B7:
#
#     sh bootstrap/selfhost/check-diverse-double-compilation.sh OUTPUT
#
#     S --seed built by cc_a--> C1 --cc_a--> A1_a --> C2_a --cc_a--> A2_a
#     S --seed built by cc_b--> C1 --cc_b--> A1_b --> C2_b --cc_b--> A2_b
#
# and the criterion is that the two toolchains disagree about the executables
# and agree about everything the compiler *says*:
#
#     C2_a == C2_b, byte for byte, and A2_a and A2_b emit identical C,
#     stdout, stderr, and exit status for every driver corpus case.
#
# This is Wheeler's diverse double compilation adapted to a compiler whose
# output is source rather than machine code. The Thompson attack it addresses
# is a host C compiler that recognizes the Kofun compiler and injects
# behaviour into it. Such a payload has to survive being regenerated by a
# compiler that an unrelated toolchain built, and it has to do so producing
# the same bytes — so a payload present in exactly one of the two toolchains
# is a C2 mismatch or a corpus disagreement, and this gate fails.
#
# What it does not establish is stated in full below and in
# bootstrap/README.md, because a security gate that overstates its reach is
# worse than none. It does not close B6: both chains run on one machine,
# against one libc and one kernel, from one checkout. A payload living below
# the C compiler is shared by both chains and survives this gate untouched.
#
# The two chains are produced by the one documented build-a1-a2.sh command
# rather than by a second copy of the generation logic. No compiler semantics
# are added here.

fail() {
    printf '%s\n' "FAIL: selfhost diverse double compilation: $*" >&2
    exit 1
}

test "$#" -eq 1 ||
    fail "usage: sh bootstrap/selfhost/check-diverse-double-compilation.sh OUTPUT"
case "$1" in
    /*) output=$1 ;;
    *) output=$PWD/$1 ;;
esac

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repo_root=$(CDPATH= cd -- "$script_dir/../.." && pwd)
cd "$repo_root"

. "$repo_root/bootstrap/selfhost/generations-lib.sh"

# The pair is declared, not discovered, so a reader of the provenance knows
# which two toolchains were actually diverse. The defaults are the pair this
# repository checks against; an operator may name another with the two
# environment variables.
cc_a=${KOFUN_DDC_CC_A:-gcc}
cc_b=${KOFUN_DDC_CC_B:-clang}

resolve_compiler() {
    resolve_name=$1
    command -v "$resolve_name" 2>/dev/null ||
        fail "diverse double compilation needs \`$resolve_name\` on PATH; name another pair with KOFUN_DDC_CC_A and KOFUN_DDC_CC_B"
}

cc_a_path=$(resolve_compiler "$cc_a")
cc_b_path=$(resolve_compiler "$cc_b")
cc_a_identity=$("$cc_a_path" --version 2>/dev/null | head -n 1)
cc_b_identity=$("$cc_b_path" --version 2>/dev/null | head -n 1)
test -n "$cc_a_identity" || fail "\`$cc_a\` reports no identity"
test -n "$cc_b_identity" || fail "\`$cc_b\` reports no identity"

# Diversity is the whole premise. Two names for one binary, or one identity
# reported twice, would make every equality below vacuous — the gate would
# pass by comparing a run against itself and read as evidence.
cc_a_real=$(readlink -f "$cc_a_path" 2>/dev/null || printf '%s' "$cc_a_path")
cc_b_real=$(readlink -f "$cc_b_path" 2>/dev/null || printf '%s' "$cc_b_path")
test "$cc_a_real" != "$cc_b_real" ||
    fail "\`$cc_a\` and \`$cc_b\` resolve to the same binary ($cc_a_real): the pair is not diverse"
test "$cc_a_identity" != "$cc_b_identity" ||
    fail "\`$cc_a\` and \`$cc_b\` report the same identity ($cc_a_identity): the pair is not diverse"

work="$output/.ddc.$$"
trap 'rm -rf "$work"' EXIT HUP INT TERM
mkdir -p "$work"

# Each chain is the documented command, under its own declared host compiler,
# writing into its own tree. build-a1-a2.sh already proves each chain
# internally reproducible and each C1 equal to the checked-in evidence.
#
# A chain that fails here is not a broken gate — it is the loudest DDC result
# there is. One toolchain reproducing the pinned evidence while the other
# cannot is exactly the asymmetry a payload in one of them produces, so the
# refusal names which toolchain disagreed and replays what it said. Swallowing
# that output would turn the most informative failure this gate can report
# into "something went wrong".
run_chain() {
    chain_label=$1
    chain_identity=$2
    chain_cc=$3
    if CC="$chain_cc" sh bootstrap/selfhost/build-a1-a2.sh "$work/$chain_label" \
        >"$work/$chain_label.stdout" 2>"$work/$chain_label.stderr"; then
        return 0
    fi
    printf '%s\n' "----- $chain_identity reported:" >&2
    tail -n 20 "$work/$chain_label.stdout" >&2 || true
    tail -n 20 "$work/$chain_label.stderr" >&2 || true
    printf '%s\n' "-----" >&2
    fail "the generation chain did not reproduce the pinned evidence under $chain_identity; if the other toolchain does reproduce it, that asymmetry is the diverse-double-compilation signal, not a flaky build"
}

run_chain chain-a "$cc_a_identity" "$cc_a_path"
run_chain chain-b "$cc_b_identity" "$cc_b_path"

# The criterion. C1 equality is implied — each chain compares its own C1
# against the checked-in evidence — and is asserted anyway, because an
# implication that stops holding should fail here rather than silently widen
# what C2 equality is taken to mean.
cmp "$work/chain-a/generations/gen1/kofun.c" \
    "$work/chain-b/generations/gen1/kofun.c" ||
    fail "C1 differs between $cc_a_identity and $cc_b_identity"
cmp "$work/chain-a/generations/gen2/kofun.c" \
    "$work/chain-b/generations/gen2/kofun.c" ||
    fail "C2 differs between $cc_a_identity and $cc_b_identity: a host C compiler changed what the Kofun compiler emits"

# Self-compilation equality alone would only say the two compilers agree
# about one program. The corpus is what says they agree about the programs
# they were built to compile, in emitted C and in both diagnostic streams.
corpus_run "$work/chain-a/generations/gen2/compiler" "$work/corpus-a2-a"
corpus_cases=$kofun_generations_corpus_cases
corpus_run "$work/chain-b/generations/gen2/compiler" "$work/corpus-a2-b"
corpus_compare "$work/corpus-a2-a" "$work/corpus-a2-b" \
    "A2 built by $cc_a" "A2 built by $cc_b"

c1_digest=$(digest_of "$work/chain-a/generations/gen1/kofun.c")
c2_digest=$(digest_of "$work/chain-a/generations/gen2/kofun.c")
c2_bytes=$(wc -c <"$work/chain-a/generations/gen2/kofun.c" | tr -d ' ')
a2_a_digest=$(digest_of "$work/chain-a/generations/gen2/compiler")
a2_b_digest=$(digest_of "$work/chain-b/generations/gen2/compiler")

# Whether the two toolchains happened to emit the same machine code is
# reported, never required. Requiring equality would make the gate a
# reproducible-build check of the host compilers, which is a different claim
# with a different owner; requiring inequality would fail the day two
# toolchains legitimately converge. Reporting it lets a reader see which
# situation produced the run in front of them.
if test "$a2_a_digest" = "$a2_b_digest"; then
    a2_executables_equal=true
else
    a2_executables_equal=false
fi

{
    printf 'schema|kofun.selfhost-diverse-double-compilation/v1\n'
    printf 'criterion|C2 byte equality and full corpus agreement across two diverse host C compilers (B7); executable equality is reported, not required\n'
    printf 'normalized_environment|%s\n' "$KOFUN_GENERATIONS_ENVIRONMENT"
    printf 'canonical_source|bootstrap/stage1/compiler.kofun\n'
    printf 'canonical_source_sha256|%s\n' \
        "$(recorded_value "$work/chain-a/provenance.tsv" canonical_source_sha256)"
    printf 'trusted_seed|bootstrap/stage2/compiler.c\n'
    printf 'trusted_seed_sha256|%s\n' \
        "$(recorded_value "$work/chain-a/provenance.tsv" trusted_seed_sha256)"
    printf 'host_compiler_a_identity|%s\n' "$cc_a_identity"
    printf 'host_compiler_b_identity|%s\n' "$cc_b_identity"
    printf 'host_compiler_flags|%s\n' "$kofun_generations_flags"
    printf 'c1_sha256|%s\n' "$c1_digest"
    printf 'c2_sha256|%s\n' "$c2_digest"
    printf 'c2_bytes|%s\n' "$c2_bytes"
    printf 'a2_a_sha256|%s\n' "$a2_a_digest"
    printf 'a2_b_sha256|%s\n' "$a2_b_digest"
    printf 'a2_executables_equal|%s\n' "$a2_executables_equal"
    printf 'corpus_cases|%s\n' "$corpus_cases"
    printf 'closes|B7\n'
    printf 'does_not_close|B6 independent clean-builder reproduction; one machine, one libc, one kernel, one checkout\n'
} >"$work/diverse-double-compilation.tsv"

rm -rf "$output/diverse-double-compilation.tsv" "$output/generations-b"
mkdir -p "$output"
cp "$work/diverse-double-compilation.tsv" \
    "$output/diverse-double-compilation.tsv"

printf 'PASS: %s and %s are distinct binaries reporting distinct identities\n' \
    "$cc_a_identity" "$cc_b_identity"
printf 'PASS: both chains built S through two generations under their own host compiler\n'
printf 'PASS: C2 (%s bytes) is byte-identical across the two toolchains\n' "$c2_bytes"
printf 'PASS: %s corpus cases agree across the two A2 compilers in C, stdout, stderr, and status\n' \
    "$corpus_cases"
printf 'report: A2 executables identical is %s (provenance, not a criterion)\n' \
    "$a2_executables_equal"
printf 'PASS: diverse double compilation holds (B7): what the Kofun compiler emits does not depend on which C compiler built it\n'
printf 'note: this does not close B6 — both chains ran on one machine, one libc, and one kernel, so a payload below the C compiler is shared and survives\n'
