#!/usr/bin/env sh
# Standard library capability matrix gate.
#
# The matrix exists so that "the standard library covers X" is a checkable
# statement rather than a habit. Three things are checked, in the order in
# which their absence would mislead most:
#
#   1. every row has exactly one valid tier and state;
#   2. every state's evidence is the kind of evidence that state permits, and
#      that evidence resolves — a `task` target that exists, a file that
#      exists, or an issue reference; and
#   3. the checker still refuses each way (1) and (2) can be broken.
#
# (3) matters as much as the rest. A checker that quietly stopped enforcing a
# rule would keep reporting PASS on an honest matrix, so every rule is proved
# by a mutation that must fail.
set -eu

ROOT=$(CDPATH= cd -P -- "$(dirname -- "$0")/.." && pwd)
MATRIX=${KOFUN_STDLIB_MATRIX:-"$ROOT/stdlib/capabilities.tsv"}
TASKFILE="$ROOT/Taskfile.yml"
WORK=${KOFUN_STDLIB_MATRIX_WORK:-"$ROOT/build/stdlib-capabilities"}

if test "$#" -gt 0; then
    printf '%s\n' "capabilities: unexpected argument: $1" >&2
    exit 2
fi

fail() {
    printf '%s\n' "capabilities: $*" >&2
    exit 1
}

rm -rf "$WORK"
mkdir -p "$WORK"

TIERS='prelude portable adapter module none'
STATES='implemented specified planned deferred non-goal'

# Validate one matrix file. Returns 0 when every row is well formed.
# Used both on the real matrix and on each deliberately broken mutation.
validate() {
    file=$1
    rows=0
    seen_jobs="$WORK/seen-jobs"
    : >"$seen_jobs"

    # Skip comments and the header row.
    while IFS='	' read -r job tier state evidence note; do
        case $job in ''|'#'*|job) continue ;; esac
        rows=$((rows + 1))

        test -n "$note" || return 1

        grep -Fxq "$job" "$seen_jobs" && return 1
        printf '%s\n' "$job" >>"$seen_jobs"

        printf '%s' "$TIERS" | tr ' ' '\n' | grep -Fxq "$tier" || return 1
        printf '%s' "$STATES" | tr ' ' '\n' | grep -Fxq "$state" || return 1

        case $state in
            implemented)
                # Evidence must be a task target that Taskfile.yml declares.
                case $evidence in
                    'task '*) ;;
                    *) return 1 ;;
                esac
                target=${evidence#task }
                grep -q "^  $target:" "$TASKFILE" || return 1
                ;;
            specified)
                # Evidence must be a spec or docs path that exists.
                case $evidence in
                    spec/*|docs/*) ;;
                    *) return 1 ;;
                esac
                test -f "$ROOT/$evidence" || return 1
                ;;
            planned|deferred)
                # Evidence must be one or more issue references.
                case $evidence in
                    '#'[0-9]*) ;;
                    *) return 1 ;;
                esac
                for ref in $evidence; do
                    case $ref in
                        '#'[0-9]*) ;;
                        *) return 1 ;;
                    esac
                done
                ;;
            non-goal)
                # A non-goal cites no artifact; the note carries the reason.
                test "$evidence" = charter || return 1
                ;;
        esac
    done <"$file"

    test "$rows" -ge 1 || return 1
    printf '%s\n' "$rows"
}

# #1454. A `planned` or `deferred` row must cite work that is still open.
#
# The state rules ask for "one or more issue references" and the shape check
# above is all that enforced it, so nine of the twelve forward-looking rows
# cited closed issues and `task stdlib` was green on every one. `planned`
# against finished work reads as "someone is on this" and means the opposite.
#
# This gate is hermetic, so it cannot ask GitHub. It does not need to:
# `artifacts/backlog/issue-state.json` is a committed snapshot of every open
# issue, regenerated by `node tests/backlog/refresh.mjs` and diffed by CI, so
# membership in it answers the question offline.
#
# Two bounds make that answer honest, and both were found by review rather
# than by me:
#
#   * The snapshot has a horizon -- the highest issue number it contains. An
#     issue filed after the snapshot was committed is open and absent, so a
#     bare membership test calls it closed. Numbers above the horizon are
#     reported as *not checked* and count for neither answer.
#   * That bound degrades in the direction that hides itself: the staler the
#     snapshot, the more rows go unchecked, until green means only that the
#     snapshot is old. So the decided count is printed and zero is a failure.
SNAPSHOT=${KOFUN_BACKLOG_SNAPSHOT:-"$ROOT/artifacts/backlog/issue-state.json"}

test -f "$SNAPSHOT" ||
    fail "backlog snapshot not found: $SNAPSHOT; regenerate with node tests/backlog/refresh.mjs"

grep -oE '"number": *[0-9]+' "$SNAPSHOT" | grep -oE '[0-9]+' | sort -un \
    >"$WORK/open-issues"
test -s "$WORK/open-issues" ||
    fail "backlog snapshot contains no issue numbers: $SNAPSHOT"
HORIZON=$(tail -n 1 "$WORK/open-issues")

# One evidence field's verdict: `live`, `closed`, or `unchecked`.
#
# The verdict is printed rather than returned, and that is the whole reason this
# function has this shape. It used to answer with an exit status -- 0 live, 1
# all-closed, 2 undecidable -- and a non-zero exit status is data the shell also
# reads as failure. `validate_liveness` is called as `$(...)`, so under `set -e`
# a shell that applies `-e` inside a command substitution kills that subshell on
# the first `unchecked` row. The gate then reported "a planned or deferred row
# cites only closed issues" while its own re-scan -- which calls the same
# function in a tested context, where `-e` does not apply -- found no such row
# and printed nothing. A failure naming a row it cannot then name is the shape
# of this bug.
#
# It stayed hidden because it needs both halves at once: `dash` applies `-e`
# inside a command substitution and `bash` does not, so it passed on a developer
# machine and failed in CI; and it needs a row citing an issue *newer* than the
# snapshot, which no row did until #1510. A verdict on stdout cannot be mistaken
# for a failure, in any shell.
citation_liveness() {
    liveness_unknown=0
    for ref in $1; do
        number=${ref#\#}
        case $number in
            ''|*[!0-9]*) continue ;;
        esac
        if grep -Fxq "$number" "$WORK/open-issues"; then
            printf 'live\n'
            return 0
        fi
        if test "$number" -gt "$HORIZON"; then
            liveness_unknown=1
        fi
    done
    if test "$liveness_unknown" -eq 0; then
        printf 'closed\n'
    else
        printf 'unchecked\n'
    fi
}

validate_liveness() {
    file=$1
    liveness_decided=0
    while IFS='	' read -r job tier state evidence note; do
        case $job in ''|'#'*|job) continue ;; esac
        case $state in planned|deferred) ;; *) continue ;; esac
        case $(citation_liveness "$evidence") in
            live) liveness_decided=$((liveness_decided + 1)) ;;
            closed) liveness_decided=$((liveness_decided + 1)); return 1 ;;
            *) ;;
        esac
        : "$tier" "$note"
    done <"$file"
    printf '%s\n' "$liveness_decided"
}

test -f "$MATRIX" || fail "matrix not found: $MATRIX"

row_count=$(validate "$MATRIX") ||
    fail "the committed matrix does not satisfy its own rules"
printf '%s\n' "PASS: $row_count capability rows carry a valid tier, state, and resolving evidence"

decided=$(validate_liveness "$MATRIX") || {
    printf '%s\n' \
        "capabilities: a planned or deferred row cites only closed issues" >&2
    while IFS='	' read -r job tier state evidence note; do
        case $job in ''|'#'*|job) continue ;; esac
        case $state in planned|deferred) ;; *) continue ;; esac
        test "$(citation_liveness "$evidence")" = closed || continue
        printf '  %s is %s against %s, all closed\n' "$job" "$state" "$evidence" >&2
        : "$tier" "$note"
    done <"$MATRIX"
    fail 'a state that describes finished work reads as "someone is on this"'
}
test "$decided" -gt 0 ||
    fail "no planned or deferred row could be decided against the snapshot; its horizon is #$HORIZON, so every citation is newer than it and this check proved nothing"
printf '%s\n' \
    "PASS: $decided planned/deferred rows cite an open issue, decided against snapshot horizon #$HORIZON"

# Every job listed in the charter's coverage goal must appear. A capability
# that is simply missing from the matrix is the failure this list prevents,
# because an absent row looks exactly like an absent problem.
REQUIRED='
collections-sequence
collections-associative
syscall-file-round-trip
process-spawn
directory-listing
directory-create
directory-remove
file-copy
file-rename
environment-authority
cli-parsing
http-server
http-client
date-time-core
clock-core
clock-adapters
time-zone-data
json
csv
toml
logging
unit-testing
benchmark-harness
concurrency
stream-protocol
buffered-io
url
hashes-checksums
compression-archive
crypto-tls
mime
temporary-files
secure-randomness
yaml
'
for job in $REQUIRED; do
    test -n "$job" || continue
    cut -f1 "$MATRIX" | grep -Fxq "$job" ||
        fail "the charter requires a row for '$job' and the matrix has none"
done
printf '%s\n' "PASS: every capability the charter names has a row"

# Negative self-tests. Each mutation breaks exactly one rule and must be
# refused; a checker that accepted any of them would still pass above.
validate_complete() {
    file=$1
    validate "$file" >/dev/null || return 1
    validate_liveness "$file" >/dev/null || return 1
    for job in $REQUIRED; do
        test -n "$job" || continue
        cut -f1 "$file" | grep -Fxq "$job" || return 1
    done
}

mutate() {
    name=$1
    shift
    out="$WORK/$name.tsv"
    cp "$MATRIX" "$out"
    "$@" "$out"
    if validate_complete "$out" >/dev/null 2>&1; then
        fail "mutation '$name' was accepted"
    fi
    printf '%s\n' "PASS [capabilities-negative] $name"
}

mutate unknown-state sed -i 's/\timplemented\ttask stdlib\t/\tshipped\ttask stdlib\t/'
mutate unknown-tier sed -i 's/\tportable\timplemented\t/\tstandard\timplemented\t/'
mutate implemented-without-task sed -i 's/\timplemented\ttask stdlib\t/\timplemented\tstdlib\/json\t/'
mutate implemented-unknown-task sed -i 's/\timplemented\ttask stdlib\t/\timplemented\ttask no-such-target\t/'
mutate missing-evidence sed -i 's/^syscall-file-round-trip\tadapter\timplemented\ttask stdlib\t/syscall-file-round-trip\tadapter\timplemented\t \t/'
mutate specified-missing-file sed -i 's|\tspecified\tspec/effects/validation-accumulation.md\t|\tspecified\tspec/effects/does-not-exist.md\t|'
# Anchored on the job id, not on the evidence value. The first version of this
# matched `\tplanned\t#555 #736\t`; re-pointing that row at a live issue in
# #1454 made the pattern miss, and a mutation that does not apply is reported
# as accepted. A mutation keyed on the thing it is about survives edits to the
# thing it mutates.
mutate planned-without-issue \
    sed -i 's|^\(concurrency\t[a-z]*\tplanned\t\)[^\t]*\t|\1soon\t|'

# #1454. The liveness rule, both ways round.
mutate planned-citing-a-closed-issue \
    sed -i 's|^\(concurrency\t[a-z]*\tplanned\t\)[^\t]*\t|\1#231\t|'
mutate non-goal-with-evidence sed -i 's/\tnon-goal\tcharter\t/\tnon-goal\ttask stdlib\t/'
mutate missing-note sed -i 's/\tTOML is the baseline config format.*$/\t/'

# A duplicate job id is how two rows can disagree about one capability.
duplicate() {
    grep -v '^#' "$1" | sed -n '2p' >>"$1"
}
mutate duplicate-job duplicate

# Row validity alone cannot detect an omitted capability, so exercise the
# charter coverage check through the same mutation boundary.
remove_required_row() {
    sed -i '/^process-spawn\t/d' "$1"
}
mutate missing-required-row remove_required_row

printf '%s\n' \
    'PASS: the capability matrix states are exact, and 12 mutations are refused'

# The must-not-fire half. A rule that refuses a row citing one closed issue
# among several open ones would be stricter than the state it models, and a
# mutation corpus made only of things that must fail cannot see that.
tolerated() {
    cp "$MATRIX" "$WORK/tolerated.tsv"
    sed -i 's|^\(concurrency\t[a-z]*\tplanned\t\)[^\t]*\t|\1#231 #1162\t|' \
        "$WORK/tolerated.tsv"
    validate_complete "$WORK/tolerated.tsv" >/dev/null 2>&1 ||
        fail 'a row citing one closed issue beside an open one was refused'
    printf '%s\n' 'PASS [capabilities-positive] one closed citation beside an open one is tolerated'
}
tolerated

# The must-not-fire half, second case: a citation *newer* than the snapshot is
# "not checked", and not-checked must not fail anything. The horizon paragraph
# above promises exactly that, and until #1510 no row exercised it.
#
# The call below is written the way the real one is -- `$(validate_liveness …)`
# guarded by `||` -- because that is where the defect was. A verdict returned as
# an exit status let `set -e` kill the substitution's subshell on the first
# unchecked row, in every shell that applies `-e` inside a command substitution.
# `dash` does and `bash` does not, so the gate passed locally and failed in CI.
# Written any other way this test would pass on the broken version.
newer_than_snapshot() {
    sed 's|^\(process-spawn\t[a-z]*\tplanned\t\)[^\t]*\t|\1#999999\t|' \
        "$MATRIX" >"$WORK/newer.tsv"
    grep -q '^process-spawn.*#999999' "$WORK/newer.tsv" ||
        fail 'the newer-than-snapshot mutation did not apply'
    newer_decided=$(validate_liveness "$WORK/newer.tsv") ||
        fail 'a citation newer than the snapshot aborted the liveness pass'
    test "$newer_decided" -eq "$((decided - 1))" ||
        fail "an unchecked citation left $newer_decided decided rows, not $((decided - 1))"
    validate_complete "$WORK/newer.tsv" >/dev/null 2>&1 ||
        fail 'a row citing an issue newer than the snapshot was refused'
    printf '%s\n' 'PASS [capabilities-positive] a citation newer than the snapshot is not checked, not refused'
}
newer_than_snapshot

# A missing snapshot must fail loudly. Absence is also what "every issue is
# closed" looks like, so a checker that skipped on a missing oracle would
# report the same green as one that looked.
absent_snapshot() {
    if KOFUN_BACKLOG_SNAPSHOT="$WORK/no-such-snapshot.json" \
        sh "$ROOT/stdlib/check-capabilities.sh" >/dev/null 2>&1
    then
        fail 'the checker passed with no backlog snapshot to read'
    fi
    printf '%s\n' 'PASS [capabilities-negative] a missing backlog snapshot fails closed'
}
absent_snapshot
