#!/bin/sh
set -eu

root=$(CDPATH= cd -- "$(dirname "$0")/../../.." && pwd)
fixtures="$root/tests/stage2/list-int-signatures"
work=${TMPDIR:-/tmp}/kofun-stage2-list-int-signatures.$$
trap 'rm -rf "$work"' EXIT HUP INT TERM
mkdir -p "$work"
ASSERT_CONTEXT='stage2 List[Int] signatures'
. "$root/tests/assertions/assert.sh"

if command -v cc >/dev/null 2>&1; then
    compiler=cc
elif command -v clang >/dev/null 2>&1; then
    compiler=clang
elif command -v gcc >/dev/null 2>&1; then
    compiler=gcc
else
    assert_fail 'a C11 compiler is required'
fi

. "$root/bootstrap/stage2/build.sh"
kofun_stage2_build "$root" "$work/kofun-stage2"

compile_success() {
    stem=$1
    source=$2
    "$work/kofun-stage2" \
        "$source" \
        "$work/$stem.c" \
        "$work/$stem.ir" \
        "$work/$stem.tokens" \
        >"$work/$stem.compile.stdout" \
        2>"$work/$stem.compile.stderr"
    assert_file_nonempty "$stem generated C" "$work/$stem.c"
    assert_file_nonempty "$stem typed IR" "$work/$stem.ir"
    assert_file_nonempty "$stem token tape" "$work/$stem.tokens"
    assert_file_empty "$stem compiler stderr" "$work/$stem.compile.stderr"
    "$compiler" -std=c11 -O2 -Wall -Wextra -Werror -pedantic \
        -I"$root/bootstrap/stage2" \
        "$work/$stem.c" -o "$work/$stem"
}

compile_success pass-return "$fixtures/pass_return.kofun"
"$work/pass-return" \
    >"$work/pass-return.stdout" 2>"$work/pass-return.stderr"
cmp "$fixtures/pass_return.stdout" "$work/pass-return.stdout"
assert_file_empty "pass/return runtime stderr" "$work/pass-return.stderr"
assert_grep \
    "List[Int] parameter reaches typed HIR" \
    -Fq '|first|immutable|List[Int]|copy|initialized|' \
    "$work/pass-return.ir"
assert_grep \
    "List[Int] returned binding reaches typed HIR" \
    -Fq '|returned|immutable|List[Int]|gc|initialized|' \
    "$work/pass-return.ir"
assert_grep \
    "declared List[Int] result position reaches the C prototype" \
    -Fq 'static KofunIntListValue kofun_fn_make_left(void);' \
    "$work/pass-return.c"
assert_grep \
    "generated by-value list parameter" \
    -Fq 'KofunIntListValue k_b2' \
    "$work/pass-return.c"
assert_grep \
    "source-order list call slots" \
    -Fq 'kofun_list_call_arg_' \
    "$work/pass-return.c"
assert_not_grep \
    "no pointer-shaped List[Int] function ABI" \
    -Eq 'kofun_fn_[^(]+\([^)]*KofunIntList[[:space:]]+\*' \
    "$work/pass-return.c"

# `List` remains an ordinary binding name outside annotation position; the
# bare-list refusal must not turn every lambda read of that spelling into a
# type diagnostic.
compile_success lambda-list-binding-name \
    "$fixtures/lambda_list_binding_name.kofun"
"$work/lambda-list-binding-name" \
    >"$work/lambda-list-binding-name.stdout" \
    2>"$work/lambda-list-binding-name.stderr"
cmp \
    "$fixtures/lambda_list_binding_name.stdout" \
    "$work/lambda-list-binding-name.stdout"
assert_file_empty \
    "List-named lambda binding runtime stderr" \
    "$work/lambda-list-binding-name.stderr"

compile_success capacity "$fixtures/capacity.kofun"
"$work/capacity" >"$work/capacity.stdout" 2>"$work/capacity.stderr"
cmp "$fixtures/capacity.stdout" "$work/capacity.stdout"
assert_file_empty "capacity runtime stderr" "$work/capacity.stderr"
assert_grep \
    "fixed 64-element by-value carrier" \
    -Fq 'int64_t elements[64]' "$work/capacity.c"

# `labelled_argument` passes its List[Int] through an external label. #1107
# widened the labelled fixed-slot lowering to the Text and List[Int] carriers
# this path already executed positionally, so it is an accept case here; the
# call-arguments gate owns the source-order and no-label-in-artifact evidence.
for stem in direct_call_return nested_calls labelled_argument
do
    compile_success "$stem" "$fixtures/$stem.kofun"
    "$work/$stem" >"$work/$stem.stdout" 2>"$work/$stem.stderr"
    cmp "$fixtures/$stem.stdout" "$work/$stem.stdout"
    assert_file_empty "$stem runtime stderr" "$work/$stem.stderr"
done

compile_success runtime-out-of-range "$fixtures/runtime_out_of_range.kofun"
set +e
"$work/runtime-out-of-range" \
    >"$work/runtime-out-of-range.stdout" \
    2>"$work/runtime-out-of-range.stderr"
runtime_status=$?
set -e
assert_num "parameter index failure status" "$runtime_status" -eq 1
assert_file_empty \
    "parameter index failure stdout" \
    "$work/runtime-out-of-range.stdout"
cmp \
    "$fixtures/runtime_out_of_range.stderr" \
    "$work/runtime-out-of-range.stderr"

# Repetition and different source directories must not alter generated C,
# typed HIR, token tapes, or observations.
mkdir -p "$work/remap-a/src" "$work/remap-b/src"
cp "$fixtures/pass_return.kofun" "$work/remap-a/src/case.kofun"
cp "$fixtures/pass_return.kofun" "$work/remap-b/src/case.kofun"
for directory in remap-a remap-b
do
    "$work/kofun-stage2" \
        "$work/$directory/src/case.kofun" \
        "$work/$directory/case.c" \
        "$work/$directory/case.ir" \
        "$work/$directory/case.tokens" \
        >"$work/$directory/compile.stdout" \
        2>"$work/$directory/compile.stderr"
    assert_file_empty \
        "$directory compiler stderr" "$work/$directory/compile.stderr"
    "$compiler" -std=c11 -O2 -Wall -Wextra -Werror -pedantic \
        "$work/$directory/case.c" -o "$work/$directory/case"
    "$work/$directory/case" \
        >"$work/$directory/runtime.stdout" \
        2>"$work/$directory/runtime.stderr"
done
cmp "$work/remap-a/case.c" "$work/remap-b/case.c"
cmp "$work/remap-a/case.ir" "$work/remap-b/case.ir"
cmp "$work/remap-a/case.tokens" "$work/remap-b/case.tokens"
cmp "$fixtures/pass_return.stdout" "$work/remap-a/runtime.stdout"
cmp "$work/remap-a/runtime.stdout" "$work/remap-b/runtime.stdout"
cmp "$work/remap-a/runtime.stderr" "$work/remap-b/runtime.stderr"

# Both available compiler families must accept and execute the generated C.
for candidate in gcc clang
do
    if command -v "$candidate" >/dev/null 2>&1; then
        # The Stage 2 translation unit intentionally emits the complete Text
        # helper set; Clang diagnoses its unused static helpers more broadly
        # than GCC, independently of the List[Int] ABI under test.
        "$candidate" -std=c11 -O2 -Wall -Wextra -Werror \
            -Wno-unused-function -pedantic \
            "$work/pass-return.c" -o "$work/pass-return-$candidate"
        "$work/pass-return-$candidate" \
            >"$work/pass-return-$candidate.stdout" \
            2>"$work/pass-return-$candidate.stderr"
        cmp \
            "$fixtures/pass_return.stdout" \
            "$work/pass-return-$candidate.stdout"
        assert_file_empty \
            "$candidate runtime stderr" \
            "$work/pass-return-$candidate.stderr"
    fi
done

# Sanitizer findings are failures. Probe support separately, then require the
# real generated program to compile and run when the toolchain supports it.
if "$compiler" -std=c11 -fsanitize=address,undefined \
    -x c -c /dev/null -o "$work/sanitizer-probe.o" >/dev/null 2>&1
then
    "$compiler" -std=c11 -O1 -g -Wall -Wextra -Werror -pedantic \
        -fsanitize=address,undefined -fno-omit-frame-pointer \
        "$work/pass-return.c" -o "$work/pass-return-sanitized"
    ASAN_OPTIONS=detect_leaks=1 UBSAN_OPTIONS=halt_on_error=1 \
        "$work/pass-return-sanitized" \
        >"$work/pass-return-sanitized.stdout" \
        2>"$work/pass-return-sanitized.stderr"
    cmp \
        "$fixtures/pass_return.stdout" \
        "$work/pass-return-sanitized.stdout"
    assert_file_empty \
        "sanitizer runtime stderr" \
        "$work/pass-return-sanitized.stderr"
fi

if "$compiler" -std=c11 -fanalyzer -x c -c /dev/null \
    -o "$work/analyzer-probe.o" >/dev/null 2>&1
then
    "$compiler" -std=c11 -O0 -Wall -Wextra -Werror -pedantic -fanalyzer \
        "$work/pass-return.c" -o "$work/pass-return-analyzed"
fi

# Typed refusals retain deterministic parsed IR/tokens but never publish C.
for stem in \
    direct_argument \
    direct_return \
    edit_parameter \
    lambda_argument \
    lambda_bare_result \
    lambda_bare_list_parameter \
    lambda_capture_index \
    lambda_capture_len \
    lambda_direct_result \
    lambda_literal \
    lambda_list_text_parameter \
    lambda_nested_list_parameter \
    lambda_parameter \
    lambda_parenthesized_result \
    list_text_parameter \
    nested_parameter \
    read_parameter \
    take_parameter
do
    for attempt in first second
    do
        set +e
        "$work/kofun-stage2" \
            "$fixtures/$stem.kofun" \
            "$work/refuse-$stem-$attempt.c" \
            "$work/refuse-$stem-$attempt.ir" \
            "$work/refuse-$stem-$attempt.tokens" \
            >"$work/refuse-$stem-$attempt.stdout" \
            2>"$work/refuse-$stem-$attempt.stderr"
        status=$?
        set -e
        assert_num "$stem $attempt refusal status" "$status" -eq 1
        assert_absent \
            "$stem $attempt rejected C" \
            "$work/refuse-$stem-$attempt.c"
        assert_file_nonempty \
            "$stem $attempt retained parsed IR" \
            "$work/refuse-$stem-$attempt.ir"
        assert_file_nonempty \
            "$stem $attempt retained tokens" \
            "$work/refuse-$stem-$attempt.tokens"
        assert_file_empty \
            "$stem $attempt compiler stderr" \
            "$work/refuse-$stem-$attempt.stderr"
        cmp \
            "$fixtures/$stem.stdout" \
            "$work/refuse-$stem-$attempt.stdout"
    done
    cmp \
        "$work/refuse-$stem-first.ir" \
        "$work/refuse-$stem-second.ir"
    cmp \
        "$work/refuse-$stem-first.tokens" \
        "$work/refuse-$stem-second.tokens"
done

# Refusal happens only after Scope HIR has recorded each constructed List as
# one exact binding type. This inventory prevents annotation brackets or
# nested element identifiers from reappearing as synthetic bindings.
for scope_case in \
    lambda_bare_list_parameter \
    lambda_parameter \
    lambda_list_text_parameter \
    lambda_nested_list_parameter
do
    "$work/kofun-stage2" --emit-scope-hir \
        "$fixtures/$scope_case.kofun" \
        "$work/$scope_case.scope-hir"
    scope_bindings=$(awk '/^binding[|]/ { count++ } END { print count + 0 }' \
        "$work/$scope_case.scope-hir")
    assert_num "$scope_case exact binding inventory" "$scope_bindings" -eq 2
    assert_not_grep \
        "$scope_case has no bracket-shaped binding" \
        -Fq '|[|immutable|' \
        "$work/$scope_case.scope-hir"
done
assert_grep \
    "lambda bare List parameter keeps its exact type" \
    -Fq '|values|immutable|List|copy|initialized|' \
    "$work/lambda_bare_list_parameter.scope-hir"
assert_grep \
    "lambda List[Int] parameter keeps its exact type" \
    -Fq '|values|immutable|List[Int]|copy|initialized|' \
    "$work/lambda_parameter.scope-hir"
assert_grep \
    "lambda List[Text] parameter keeps its exact type" \
    -Fq '|values|immutable|List[Text]|copy|initialized|' \
    "$work/lambda_list_text_parameter.scope-hir"
assert_grep \
    "nested lambda List parameter keeps its exact type" \
    -Fq '|values|immutable|List[List[Int]]|copy|initialized|' \
    "$work/lambda_nested_list_parameter.scope-hir"

# The unsupported local path has the same load-bearing partial-fact contract:
# one List[Text] binding with GC ownership and no candidate use for `Text`.
local_list_source="$root/tests/stage2/list-int-values/unsupported_annotation.kofun"
"$work/kofun-stage2" --emit-scope-hir \
    "$local_list_source" \
    "$work/local-list-text.scope-hir"
local_list_bindings=$(awk \
    '/^binding[|]/ { count++ } END { print count + 0 }' \
    "$work/local-list-text.scope-hir")
local_list_candidates=$(awk \
    '/^candidate-use[|]/ { count++ } END { print count + 0 }' \
    "$work/local-list-text.scope-hir")
assert_num "local List[Text] exact binding inventory" \
    "$local_list_bindings" -eq 1
assert_num "local List[Text] has no annotation candidate uses" \
    "$local_list_candidates" -eq 0
assert_grep \
    "local List[Text] keeps its exact type and ownership" \
    -Fq '|values|immutable|List[Text]|gc|initialized|' \
    "$work/local-list-text.scope-hir"

# The public four-argument compiler maps every refusal to process status 1.
# Its orchestration-only outcome mode preserves status 3 for exactly the
# ownership-mode boundary so `kofun check` can delegate to the established
# Copy/borrow validator without classifying unrelated E2S157 refusals.
set +e
"$work/kofun-stage2" --compile-outcome \
    "$fixtures/read_parameter.kofun" \
    "$work/read-outcome.c" \
    "$work/read-outcome.ir" \
    "$work/read-outcome.tokens" \
    >"$work/read-outcome.stdout" \
    2>"$work/read-outcome.stderr"
read_outcome_status=$?
set -e
assert_num "read ownership compile outcome" "$read_outcome_status" -eq 3
assert_absent "read ownership rejected C" "$work/read-outcome.c"
assert_file_empty "read ownership outcome stderr" "$work/read-outcome.stderr"
cmp "$fixtures/read_parameter.stdout" "$work/read-outcome.stdout"

# The Kofun authority and audited C seed must carry this semantic family
# together; the checksum gate then pins their exact bytes.
assert_grep \
    "canonical Kofun List[Int] signature family" \
    -Fq 'fn direct_list_int_call_supported(' \
    "$root/bootstrap/stage2/compiler.kofun"
assert_grep \
    "audited C List[Int] signature family" \
    -Fq 'static bool direct_list_int_call_supported(' \
    "$root/bootstrap/stage2/compiler.c"
assert_grep \
    "canonical Kofun literal-boundary diagnostic" \
    -Fq 'bind a List[Int] literal before passing or returning it' \
    "$root/bootstrap/stage2/compiler.kofun"
assert_grep \
    "audited C literal-boundary diagnostic" \
    -Fq 'bind a List[Int] literal before passing or returning it' \
    "$root/bootstrap/stage2/compiler.c"
assert_grep \
    "canonical Kofun lambda-boundary validation" \
    -Fq 'fn validate_list_int_lambda_uses(' \
    "$root/bootstrap/stage2/compiler.kofun"
assert_grep \
    "audited C lambda-boundary validation" \
    -Fq 'static char *validate_list_int_lambda_uses(' \
    "$root/bootstrap/stage2/compiler.c"
node --check "$fixtures/check-pair.mjs"
node "$fixtures/check-pair.mjs" \
    "$root/bootstrap/stage2/compiler.c" \
    "$root/bootstrap/stage2/compiler.kofun" \
    self-test

(
    cd "$root"
    sha256sum -c bootstrap/stage2/SHA256SUMS
)

echo "PASS: Stage 2 List[Int] parameters/results use bounded by-value C11 carriers"
