#!/usr/bin/env sh
set -eu

# What compiles a `c11-stage1` conformance result.
#
# The adapter used to call `bin/kofun emit-c`, which runs the Stage 2 compiler
# first and falls back to Stage 1 only for compile-outcome status 3. So a
# source Stage 2 accepted was compiled by Stage 2 and reported under the Stage 1
# backend's name. Measured on the audited base: the `functions` corpus was
# `supported` for `c11-stage1`, and five of its twelve cases were Stage 2
# compilations — the emitted C said so in its first line, `/* Generated by the
# Kofun-written Stage 2 Core lowerer. */`, while the row above it claimed
# Stage 1.
#
# Nothing caught it, for two reasons that both had to be fixed. The adapter had
# no way to tell which compiler answered it; and no gate ran the shared runner
# for these corpora at all, so the rows citing `tests/conformance/run.sh` as
# their evidence cited a command nothing executed. This file is that command.
#
# It refuses in the two directions that matter: the compiler on the adapter's
# path is not the Stage 1 seed, and a source only Stage 2 accepts is reported as
# anything other than unsupported.

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/../../.." && pwd)
WORK=${KOFUN_STAGE1_ADAPTER_WORK:-"$ROOT/build/${KOFUN_GATE_WORK_NAMESPACE:+$KOFUN_GATE_WORK_NAMESPACE/}conformance-stage1-adapter"}
ADAPTER="$ROOT/tests/conformance/backends/c11-stage1.sh"
CC=${CC:-cc}
ASSERT_CONTEXT=stage1-adapter
. "$ROOT/tests/assertions/assert.sh"

rm -rf "$WORK"
mkdir -p "$WORK"

STAGE1_BANNER='/* Generated by the Kofun-written Stage 1 seed compiler. */'
STAGE2_BANNER='/* Generated by the Kofun-written Stage 2 Core lowerer. */'

# ---------------------------------------------------------------------------
# 1. The public driver's fallback is not on the adapter's path.
#
# A static reading, because the point is that the command is absent rather than
# that it happened not to run today. `bin/kofun` reaches Stage 1 only through
# Stage 2, so a command that names it is the defect, whatever it does next.
# Comments are stripped first: the adapter explains what it stopped doing, and
# that explanation is the part worth keeping.
# ---------------------------------------------------------------------------
grep -v '^[[:space:]]*#' "$ADAPTER" >"$WORK/adapter.commands"
assert_not_grep "c11-stage1 adapter commands" -Fq \
    'emit-c' "$WORK/adapter.commands"
assert_not_grep "c11-stage1 adapter commands" -Fq \
    'bin/kofun' "$WORK/adapter.commands"

# ---------------------------------------------------------------------------
# 2. The compiler the adapter builds is the Stage 1 seed, and it is built once.
#
# `cc` is wrapped so every compile is recorded. Twelve numeric cases each
# compile their own emitted C; the seed itself must appear exactly once.
#
# The runner is not narrowed to this one backend, tempting as that is for a
# gate that only asks about this one backend. `KOFUN_CONFORMANCE_BACKENDS`
# would need a `capabilities.tsv` listing exactly the adapters in that
# directory, and a second capability table is a second authority — the thing
# `tests/conformance/numeric/README.md` says must not exist.
# ---------------------------------------------------------------------------
KOFUN_STAGE1_CC_LOG="$WORK/cc.log"
KOFUN_STAGE1_CC_REAL=$CC
export KOFUN_STAGE1_CC_LOG KOFUN_STAGE1_CC_REAL
: >"$KOFUN_STAGE1_CC_LOG"

CC="$ROOT/tests/conformance/stage1-adapter/cc-count-wrapper.sh" \
KOFUN_CONFORMANCE_STAGE1_WORK="$WORK/seed" \
    sh "$ROOT/tests/conformance/run.sh" "$ROOT/tests/conformance/numeric" \
    >"$WORK/numeric.stdout" 2>"$WORK/numeric.stderr"

assert_grep "numeric.stdout" -Fq \
    'coverage: 12/12 cases executed by c11-stage1' "$WORK/numeric.stdout"
assert_grep "numeric.stdout" -Fq \
    'refused: 3/12 cases refused before execution by c11-stage1' \
    "$WORK/numeric.stdout"
# Scoped to this backend's own lines. The runner covers every adapter, and a
# failure belonging to another one should be reported by that backend's gate
# rather than arrive here wearing this one's name.
grep -F 'c11-stage1' "$WORK/numeric.stdout" >"$WORK/numeric.c11-stage1" || true
assert_not_grep "numeric c11-stage1 lines" -Fq \
    'FAIL' "$WORK/numeric.c11-stage1"

seed_compiles=$(
    grep -c 'bootstrap/stage1/compiler\.c' "$KOFUN_STAGE1_CC_LOG" || true
)
assert_num "Stage 1 seed compiles during one runner" "$seed_compiles" -eq 1
assert_executable "built Stage 1 seed" "$WORK/seed/kofun-stage1"
assert_eq "built seed identity" \
    "$("$WORK/seed/kofun-stage1" | sed -n 1p)" \
    'usage: kofun-stage1 INPUT.kofun OUTPUT.c'

unset KOFUN_STAGE1_CC_LOG KOFUN_STAGE1_CC_REAL

# ---------------------------------------------------------------------------
# 3. A Stage 2-only source is unsupported, and says so with 125.
#
# Both sentinels are valid Kofun that Stage 2 compiles and executes. The
# capability table keeps their corpora away from this backend, so the shared
# runner never asks; this asks directly, which is the only way a table row can
# be wrong safely.
# ---------------------------------------------------------------------------
run_adapter_case() (
    adapter=$1
    source=$2
    case_work=$3

    rm -rf "$case_work"
    mkdir -p "$case_work"

    KOFUN_ROOT=$ROOT
    export KOFUN_ROOT
    KOFUN_CONFORMANCE_STAGE1_WORK="$WORK/seed"
    export KOFUN_CONFORMANCE_STAGE1_WORK

    . "$adapter"

    available_status=0
    backend_check_available \
        >"$case_work/available.stdout" 2>"$case_work/available.stderr" ||
        available_status=$?
    set -e
    if test "$available_status" -ne 0; then
        printf '%s\n' "$available_status" >"$case_work/status"
        printf 'unavailable\n' >"$case_work/stage"
        exit 0
    fi

    compile_status=0
    backend_compile "$source" "$case_work/program" "$case_work" \
        >"$case_work/compile.stdout" 2>"$case_work/compile.stderr" ||
        compile_status=$?
    set -e
    printf '%s\n' "$compile_status" >"$case_work/status"
    printf 'compiled\n' >"$case_work/stage"
)

assert_unsupported_sentinel() {
    label=$1
    source=$2
    case_work="$WORK/sentinel-$label"

    run_adapter_case "$ADAPTER" "$source" "$case_work"
    assert_eq "$label reached compilation" \
        "$(cat "$case_work/stage")" compiled
    assert_num "$label adapter status" "$(cat "$case_work/status")" -eq 125
    assert_absent "$label emitted C" "$case_work/program.c"
    assert_absent "$label executable" "$case_work/program"
    assert_file_nonempty "$label diagnostic" "$case_work/compile.stdout"
}

assert_unsupported_sentinel decimal \
    "$ROOT/tests/conformance/decimal-arithmetic/decimal_exactness.kofun"
assert_unsupported_sentinel const-generics \
    "$ROOT/tests/conformance/const-generics/fixed_scale_instantiation.kofun"

# Both sentinels really are sources Stage 2 accepts. Without this the two
# assertions above would also pass for a source nothing can compile, which
# proves nothing about the fallback.
"$ROOT/bin/kofun" emit-c \
    "$ROOT/tests/conformance/decimal-arithmetic/decimal_exactness.kofun" \
    "$WORK/decimal-stage2.c" >"$WORK/decimal-stage2.stdout" 2>&1
assert_grep "decimal-stage2.c" -Fqx "$STAGE2_BANNER" "$WORK/decimal-stage2.c"

# ---------------------------------------------------------------------------
# 4. The refusals, proved by reintroducing what they refuse.
#
# A gate that only reads the good path cannot tell whether it still refuses the
# bad one. Each mutation below is the defect this issue removed, applied to a
# scratch copy, and each must fail.
# ---------------------------------------------------------------------------

# 4a. The public driver restored. Its fallback compiles and runs the Decimal
# sentinel through Stage 2, so the adapter returns success where it must return
# 125. The include path is the same support boundary the real c11-stage2
# adapter supplies for emitted C's `#include "decimal_v1.c"`.
mkdir -p "$WORK/mutant-driver"
cat >"$WORK/mutant-driver/c11-stage1.sh" <<'MUTANT'
BACKEND_NAME=c11-stage1
STAGE1_COMPILER=
backend_check_available() {
    STAGE1_COMPILER=driver
}
backend_compile() {
    source=$1
    output=$2
    work=$3
    emitted="$work/program.c"
    set +e
    "$KOFUN_ROOT/bin/kofun" emit-c "$source" "$emitted" \
        >"$work/emit.stdout" 2>"$work/emit.stderr"
    emit_status=$?
    set -e
    test "$emit_status" -eq 0 || return 1
    "${CC:-cc}" -std=c11 -O2 -Wall -Wextra -Werror \
        -I"$KOFUN_ROOT/bootstrap/stage2" \
        "$emitted" -o "$output"
}
MUTANT

assert_restored_driver_success() {
    label=$1
    case_work=$2

    assert_num "$label compile status" \
        "$(cat "$case_work/status")" -eq 0
    assert_grep "$label emitted C" -Fqx \
        "$STAGE2_BANNER" "$case_work/program.c"
    assert_executable "$label executable" "$case_work/program"

    run_status=0
    "$case_work/program" \
        >"$case_work/actual.stdout" 2>"$case_work/actual.stderr" ||
        run_status=$?
    assert_num "$label runtime status" "$run_status" -eq 0
    printf '1\n1\n1\n1\n' >"$case_work/expected.stdout"
    if ! cmp -s "$case_work/expected.stdout" "$case_work/actual.stdout"; then
        assert_fail "$label runtime stdout: expected four exact Decimal observations"
    fi
    assert_file_empty "$label runtime stderr" "$case_work/actual.stderr"
}

run_adapter_case "$WORK/mutant-driver/c11-stage1.sh" \
    "$ROOT/tests/conformance/decimal-arithmetic/decimal_exactness.kofun" \
    "$WORK/mutant-driver-case"
assert_restored_driver_success \
    "restored driver Decimal sentinel" "$WORK/mutant-driver-case"

# Removing that support boundary must trip the exact-success assertion by
# name. This is the lasting mutation for the original false positive: status 1
# can no longer satisfy the proof merely because it differs from 125.
mkdir -p "$WORK/mutant-driver-missing-support"
sed '/-I"\$KOFUN_ROOT\/bootstrap\/stage2"/d' \
    "$WORK/mutant-driver/c11-stage1.sh" \
    >"$WORK/mutant-driver-missing-support/c11-stage1.sh"
assert_not_grep "missing-support driver" -Fq -- \
    '-I"$KOFUN_ROOT/bootstrap/stage2"' \
    "$WORK/mutant-driver-missing-support/c11-stage1.sh"
run_adapter_case "$WORK/mutant-driver-missing-support/c11-stage1.sh" \
    "$ROOT/tests/conformance/decimal-arithmetic/decimal_exactness.kofun" \
    "$WORK/mutant-driver-missing-support-case"
assert_grep "missing-support compiler diagnostic" -Fq \
    'decimal_v1.c' \
    "$WORK/mutant-driver-missing-support-case/compile.stderr"
assert_absent "missing-support executable" \
    "$WORK/mutant-driver-missing-support-case/program"

missing_support_proof_status=0
(
    assert_restored_driver_success \
        "restored driver Decimal sentinel" \
        "$WORK/mutant-driver-missing-support-case"
) >"$WORK/missing-support-proof.stdout" \
    2>"$WORK/missing-support-proof.stderr" ||
    missing_support_proof_status=$?
assert_num "missing Stage 2 support fails restored-driver proof" \
    "$missing_support_proof_status" -eq 1
assert_grep "missing Stage 2 support names exact compile-status failure" -Fqx \
    'FAIL: stage1-adapter: restored driver Decimal sentinel compile status: expected -eq 0, got 1' \
    "$WORK/missing-support-proof.stderr"

# 4b. The same restored driver against a source both stages accept. The real
# adapter reads the provenance banner, so this one fails on an ordinary numeric
# case rather than only on the sources Stage 1 cannot reach — which is what
# makes the check load-bearing instead of decorative.
mkdir -p "$WORK/mutant-banner"
sed 's|"\$STAGE1_COMPILER" "\$source" "\$emitted" \\|"$KOFUN_ROOT/bin/kofun" emit-c "$source" "$emitted" \\|' \
    "$ADAPTER" >"$WORK/mutant-banner/c11-stage1.sh"
assert_grep "banner mutant" -Fq 'bin/kofun' "$WORK/mutant-banner/c11-stage1.sh"
run_adapter_case "$WORK/mutant-banner/c11-stage1.sh" \
    "$ROOT/tests/conformance/numeric/int64_boundaries.kofun" \
    "$WORK/mutant-banner-case"
assert_num "banner mutant on an ordinary case" \
    "$(cat "$WORK/mutant-banner-case/status")" -eq 1
assert_grep "banner mutant diagnostic" -Fq \
    'emitted C was not produced by the Stage 1 seed' \
    "$WORK/mutant-banner-case/compile.stderr"
assert_absent "banner mutant emitted C" "$WORK/mutant-banner-case/program.c"

# 4c. A substituted compiler. The Stage 2 binary is a real compiler that
# answers to the same two operands, so nothing but an identity check separates
# it from the seed.
. "$ROOT/bootstrap/stage2/build.sh"
kofun_stage2_build "$ROOT" "$WORK/kofun-stage2"
substituted_status=0
(
    KOFUN_STAGE1_COMPILER="$WORK/kofun-stage2"
    export KOFUN_STAGE1_COMPILER
    KOFUN_ROOT=$ROOT
    export KOFUN_ROOT
    . "$ADAPTER"
    backend_check_available
) >"$WORK/substituted.stdout" 2>"$WORK/substituted.stderr" ||
    substituted_status=$?
assert_ne "substituted Stage 2 binary is refused" "$substituted_status" 0
assert_grep "substituted.stderr" -Fq 'is not the Stage 1 seed' \
    "$WORK/substituted.stderr"

# 4d. A reuse path that names nothing. Failing closed matters more here than
# anywhere else: a stale reuse that silently rebuilds is a stale reuse nobody
# ever discovers.
missing_status=0
(
    KOFUN_STAGE1_COMPILER="$WORK/there-is-no-such-compiler"
    export KOFUN_STAGE1_COMPILER
    KOFUN_ROOT=$ROOT
    export KOFUN_ROOT
    . "$ADAPTER"
    backend_check_available
) >"$WORK/missing.stdout" 2>"$WORK/missing.stderr" || missing_status=$?
assert_ne "missing reuse path is refused" "$missing_status" 0
assert_grep "missing.stderr" -Fq 'not an executable file' "$WORK/missing.stderr"

# 4e. A supplied seed is used rather than rebuilt, which is the whole point of
# the reuse contract.
KOFUN_STAGE1_CC_LOG="$WORK/cc-reuse.log"
KOFUN_STAGE1_CC_REAL=$CC
export KOFUN_STAGE1_CC_LOG KOFUN_STAGE1_CC_REAL
: >"$KOFUN_STAGE1_CC_LOG"
(
    KOFUN_STAGE1_COMPILER="$WORK/seed/kofun-stage1"
    export KOFUN_STAGE1_COMPILER
    KOFUN_ROOT=$ROOT
    export KOFUN_ROOT
    KOFUN_CONFORMANCE_STAGE1_WORK="$WORK/reuse"
    export KOFUN_CONFORMANCE_STAGE1_WORK
    CC="$ROOT/tests/conformance/stage1-adapter/cc-count-wrapper.sh"
    export CC
    . "$ADAPTER"
    backend_check_available
) >"$WORK/reuse.stdout" 2>"$WORK/reuse.stderr"
reuse_compiles=$(
    grep -c 'bootstrap/stage1/compiler\.c' "$KOFUN_STAGE1_CC_LOG" || true
)
assert_num "seed compiles when one is supplied" "$reuse_compiles" -eq 0
assert_executable "reused Stage 1 seed" "$WORK/reuse/kofun-stage1"
unset KOFUN_STAGE1_CC_LOG KOFUN_STAGE1_CC_REAL

# ---------------------------------------------------------------------------
# 5. The capability table says what the seed can actually do.
#
# `functions` was `supported` and is not: three constructs in that corpus are
# outside the Stage 1 Core, and the row was carried by Stage 2. The reason
# column is checked against the seed rather than trusted, so it cannot drift
# into prose that stopped being true.
# ---------------------------------------------------------------------------
capability_state=$(
    awk -F '	' '$1 == "c11-stage1" && $2 == "functions" { print $3; exit }' \
        "$ROOT/tests/conformance/capabilities.tsv"
)
assert_eq "c11-stage1 functions capability" "$capability_state" unsupported

refuses() {
    label=$1
    body=$2
    printf '%s\n' "$body" >"$WORK/probe.kofun"
    probe_status=0
    "$WORK/seed/kofun-stage1" "$WORK/probe.kofun" "$WORK/probe.c" \
        >"$WORK/probe.stdout" 2>"$WORK/probe.stderr" || probe_status=$?
    assert_ne "Stage 1 refuses $label" "$probe_status" 0
    assert_absent "$label emitted C" "$WORK/probe.c"
    rm -f "$WORK/probe.c"
}

accepts() {
    label=$1
    body=$2
    printf '%s\n' "$body" >"$WORK/probe.kofun"
    "$WORK/seed/kofun-stage1" "$WORK/probe.kofun" "$WORK/probe.c" \
        >"$WORK/probe.stdout" 2>"$WORK/probe.stderr"
    assert_grep "$label emitted C" -Fqx "$STAGE1_BANNER" "$WORK/probe.c"
    rm -f "$WORK/probe.c"
}

accepts "five parameters" 'fn f(a: Int, b: Int, c: Int, d: Int, e: Int) -> Int {
    return a + b + c + d + e
}

fn main() {
    print(f(1, 2, 3, 4, 5))
}'
refuses "a sixth parameter" 'fn f(a: Int, b: Int, c: Int, d: Int, e: Int, g: Int) -> Int {
    return a + b + c + d + e + g
}

fn main() {
    print(f(1, 2, 3, 4, 5, 6))
}'
accepts "main returning Void" 'fn main() {
    print(1)
}'
refuses "main returning Int" 'fn main() -> Int {
    print(1)
    return 0
}'
accepts "unary minus as the whole result" 'fn f(a: Int) -> Int {
    return -a
}

fn main() {
    print(f(2))
}'
refuses "unary minus as a binary operand" 'fn f(a: Int) -> Int {
    return 2 * -a
}

fn main() {
    print(f(2))
}'

printf '%s\n' \
    "PASS: the c11-stage1 adapter runs the Stage 1 seed and no public-driver fallback" \
    "PASS: the seed is built once per runner, reused when supplied, and fails closed otherwise" \
    "PASS: Stage 2-only Decimal and const-generic sources are unsupported, with no artifact" \
    "PASS: a restored driver succeeds exactly, and missing Stage 2 support fails its proof by name" \
    "PASS: a substituted binary and a missing reuse path are each refused" \
    "PASS: the c11-stage1 functions row matches what the seed accepts, construct by construct"
