# Adapter for the active Kofun-written Stage 1 C11 backend.
#
# This invokes the Stage 1 seed itself. It used to call `bin/kofun emit-c`,
# which runs the Stage 2 compiler first and falls back to Stage 1 only for
# compile-outcome status 3 — so every source Stage 2 accepts was compiled by
# Stage 2 while carrying this backend's name. None of the recorded results were
# wrong, because `capabilities.tsv` keeps the Decimal and const-generic corpora
# away from this backend. But the thing preventing the false evidence was the
# capability table, not the adapter: moving one row to `supported` would have
# produced a green Stage 1 result out of a Stage 2 compilation. The row is a
# statement about the backend, and it has to be able to be wrong safely.

BACKEND_NAME=c11-stage1

# The seed for this run. `backend_check_available` builds it once; every
# `backend_compile` after that only reads this variable. Both run in the
# runner's per-backend subshell, so one build covers the whole corpus rather
# than one per fixture.
STAGE1_COMPILER=

backend_check_available() {
    . "$KOFUN_ROOT/bootstrap/stage1/build.sh"

    stage1_work=${KOFUN_CONFORMANCE_STAGE1_WORK:-"$KOFUN_ROOT/build/${KOFUN_GATE_WORK_NAMESPACE:+$KOFUN_GATE_WORK_NAMESPACE/}conformance-c11-stage1"}
    mkdir -p "$stage1_work" || return 1

    # A failure here returns 1 and not 125. 125 means the host cannot run this
    # backend's executables, which downgrades every case to a build-only pass;
    # a compiler that could not be produced or could not be identified is a
    # gate failure, and has to be loud.
    kofun_stage1_build "$KOFUN_ROOT" "$stage1_work/kofun-stage1" || return 1
    STAGE1_COMPILER="$stage1_work/kofun-stage1"
}

backend_compile() {
    source=$1
    output=$2
    work=$3
    emitted="$work/program.c"

    test -n "$STAGE1_COMPILER" || {
        printf '%s\n' \
            "c11-stage1: no Stage 1 compiler; backend_check_available did not run" >&2
        return 1
    }

    set +e
    "$STAGE1_COMPILER" "$source" "$emitted" \
        >"$work/emit.stdout" 2>"$work/emit.stderr"
    emit_status=$?
    set -e
    if test "$emit_status" -ne 0; then
        cat "$work/emit.stdout" "$work/emit.stderr"
        # The seed refuses with a registered diagnostic, status 1, and no
        # emitted C. Its Core is its acceptance set, so a refusal is this
        # backend declining the source rather than the source being broken —
        # which is what 125 says. Any other failure is not a refusal and must
        # not be reported as one.
        if test "$emit_status" -eq 1 &&
           test ! -e "$emitted" &&
           grep -q '^error\[' "$work/emit.stdout"
        then
            return 125
        fi
        return 1
    fi

    # Every compiler in this repository stamps the C it emits with its own
    # name, so the artifact says which one made it. Asking here is what makes
    # this adapter unable to report a Stage 2 compilation under a Stage 1
    # name: put `bin/kofun emit-c` back on the line above and the very first
    # case fails, instead of only the ones Stage 2 happens to accept and
    # Stage 1 does not.
    if ! head -n 1 "$emitted" | grep -Fqx \
        '/* Generated by the Kofun-written Stage 1 seed compiler. */'
    then
        printf '%s\n' \
            "c11-stage1: emitted C was not produced by the Stage 1 seed" >&2
        head -n 1 "$emitted" >&2
        rm -f "$emitted"
        return 1
    fi

    compiler=${CC:-cc}
    "$compiler" -std=c11 -O2 -Wall -Wextra -Werror \
        "$emitted" -o "$output"
}
